### ISSUE TITLE
Topaz & Numby Follow Up Attack Energy Generation

### ISSUE THREAD

**Issue by ProtoJ17** [djordje-kalojevic/HSR-Optimal-Rotation-Calculator#13]
The calculator seems to assume that Numby's independent action generates 10 energy for Topaz in addition to the 10 from her trace and 5 from e2. This makes sense assuming Topaz's follow up attack works like others which generate 10 to 5 energy (eg Himeko, Dr.Ratio, Herta) but numby's follow up attack / action does not generate any energy for Topaz outside of e2 and Windfall Bonanza (trace). This causes the calc to state that a near perfect uptime for Topaz's ultimate is possible at e2 while energy regeneration is at 119% so long as she recives one blow or uses skill twice. However, perfect uptime is not possible without e6 as 3 actions are needed. I would also like to request that the option for selecting the number of follow up attacks performed be selectable separately from the option to choose eidolon level.

1. Select character Topaz
2. Select eidolon level 2
3. Select 2 follow up attacks
4. Select 5 star energy link rope
5. Select 1 attack received 
6. Toggle Ultimate activation and energy breakdown/breakpoints
7. Begin Calculation 
-Calculator states optimal rotation is 1 Skill > 1 Basic

True Calculation
5 (ultimate)
2(10+5) (2 windfall bonanza numby actions with trace/e2)
30 (skill)
20 (basic)
10 (Blow received)
95x1.19 (~19 energy regeneration)
                Final Energy
~113.05 (one more action needed/e6)

Current Calculation
5 (ultimate)
2(10+10+5) (2 windfall bonanza numby actions with trace/e2 assuming base numby actions generate 10 energy)
30 (skill)
20 (basic)
10 (Blow received)
115x1.19 (~19% energy regeneration)
                  Final energy
~136.85 (2 action ultimate rotation)

Some information seems to be committed from the Calculation (trace and eidolon energy gain) but this seems to be what the calculator is doing.

![Screenshot (1)](https://github.com/djordje-kalojevic/HSR-Optimal-Rotation-Calculator/assets/161399174/ae310776-94b0-40f8-907c-977862bef217)

![Screenshot_20240226_182509_Brave](https://github.com/djordje-kalojevic/HSR-Optimal-Rotation-Calculator/assets/161399174/06ec16bd-f0e2-4662-96b5-a894907fbce0)

**Comment by djordje-kalojevic** [comment]
Hi ProtoJ17,

First of all, I would like to thank you for reaching out and for this very detailed breakdown.

You are correct, Topaz's calculations have a few issues. For one, under the hood the energy gained was accidentally doubled if Topaz was E2, i.e., 10 per follow-up attack (FUA) at base instead of 5, hence the "Follow-ups: 11.944" (10 + 19.44%) in the Detailed Breakdown. Secondly, Ultimate already assumes 2 FUA (one per turn), so selecting the additional 2 FUA via GUI results in 4 FUAs.
 
This is what I have already done to improve them (if you have any further suggestions, feel free to add them):
1) Fixed the doubling of base energy gained from Numby's FUAs
2) Added the missing A6 Trace and added the option to enable/disable it like other traces
3) Added the missing E6
4) Added the option to select the number of FUAs without the E2 (since Numby can generate energy at E0 with A6 trace). This will be on top of the 2 (3 with E6) FUAs from the Ultimate. I have also added a tooltip to reflect this.

I do not have Topaz so if there is any other issue with this approach please do let me know.

I am a bit sick at the moment, but I will try to have the new version up tomorrow, after some more testing. This version will also include Black Swan and Sparkle (luckily they are a lot easier to calculate than Topaz lol). Of course, you will be credited for helping with this!

Thank you once again for reaching out.

**Comment by ProtoJ17** [comment]
I honestly didn't expect to get a response back, let alone receive one so
quickly! Thanks a million honestly. Also with a free ratio, Aventurine on
the way and whispers about Jade, an IPC FuA erudition unit, coming in the
future; I would definitely recommend maybe picking her up on a rerun.
There's an IPC team on the horizon.

**Comment by djordje-kalojevic** [comment]
I would've responded even sooner, but had to refamiliarize myself with the way I had implemented Topaz as it was a while ago, and because I even had to step back from coding due to real life stuff. Hence why I am still to release Black Swan (but I am at least releasing Sparkle ahead of the schedule lol)

I have around 500+ pulls saved but idk whom to get tbh.. current top runners are: Sparkle, Acheron, Aventurine, Sam, JL (missed her banner unfortunately..), maybe even a LC or two.

**Comment by ProtoJ17** [comment]
Apparently my mates Seele hits 300 crit damage with 100 rate with Sparkle.... I'm a little jealous. Maybe you should get her?

**Comment by djordje-kalojevic** [comment]
I pulled her a few days ago and she's been amazing ever since, makes my Blade shine again. Now waiting to see if I can get E1 Bronya from the anniversary or if I should be picking her from the standard 300 pull rewards.

Also I have just released the new version, took a bit longer as I wanted to cram even more stuff, anyway if you ever notice anything off, feel free to make an issue or DM me.
